# Generated by Django 5.0.1 on 2024-02-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='c5c14185', max_length=20, unique=True),
        ),
    ]
