# Generated by Django 5.0.1 on 2024-02-18 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_author_alter_book_book_id_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='ac6aaf5a', max_length=20, unique=True),
        ),
    ]
