# Generated by Django 5.0.1 on 2024-02-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_author_id_alter_book_author_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='95ee41e0', max_length=20, unique=True),
        ),
    ]
